### ISSUE TITLE
Bump Java version to 17

### ISSUE THREAD

**Issue by rmcdouga** [RPTools/dicelib#121]
I'd like to submit a PR to bump dicelib's Java version from 16 to 17.

Background:  I forked MapTool which depends on dicelib, but I only have Java 17 installed.  Rather than going back and installing Java 16 (which is no longer supported), I'd prefer to bring dicelib up to Java 17.

I updated the files and got it building, so I'd like to submit it as a PR.  It was a fairly trivial change however I am new to gradle, so be aware, I may have missed something that wasn't necessary but is a best practice.  I'll be happy to make any additional changes you require.

**Comment by cwisniew** [comment]
Thanks for the contribution

Please submit PR with link back to this issue and we can merge (or provide feedback if any is required).
