### ISSUE TITLE
New dice expressions to reroll exactly once, and either keep the new value or choose the higher

### ISSUE THREAD

**Issue by selquest** [RPTools/dicelib#27]
**Is your feature request related to a problem? Please describe.**
D&D 5th edition (and likely other systems) has a number of features that allow for dice below a certain threshold to be rerolled **once**, and either the new value must be kept or a choice is allowed to take the higher.  The existing `2d6r3` syntax doesn't work here, as dice are rerolled repeatedly until all results are at least the threshold.

**Describe the solution you'd like**

- A new expression syntax like `2d6rk3` to reroll dice exactly once, and force the use of the new value.
- A new expression syntax like `2d6rc3` to reroll dice exactly once, and choose the higher result

**Describe alternatives you've considered**
This is currently achievable through macros checking the values in `getNewRolls()`, but would be much easier to manipulate in framework implementations as a dice expression.

**Comment by Phergus** [comment]
Appears to be a bug when more than one die is less than keep value.
`[2d5rk3]` returned `5` though `[getNewRolls()]` showed `[1,2,1,3]`. Result should be 4 as both of th second rolls should be used.

Also saw return of `7` with `getNewRolls()` of `[2,2,1,5]`.  Result should be 6.

For `[2d6rc3]`, it appears to be rerolling the rerolls
Result of `9` with `getNewRolls()` of [2,6,2,3]

Also saw result of `8` with `getNewRolls()` of `[2,2,6]`. Should have been two rerolls.

**Comment by selquest** [comment]
I'll take a look - I thought I'd tested that scenario, but it's definitely possible I missed something.

**Comment by selquest** [comment]
@Phergus confirmed working as expected.  The confusion here is that it re-rolls each die immediately in sequence - the same way the repeating `reroll()` function does.

**Comment by Phergus** [comment]
That's it.  Didn't realize it was doing the rerolls immediately.

Tested.  Rolls performing as expected.

**Comment by selquest** [comment]
Updated wiki page for Dice Expressions, added page for `rerollOnce()` function
