### ISSUE TITLE
getRolled() and getNewRolls() broken in UDFs

### ISSUE THREAD

**Issue by selquest** [RPTools/dicelib#38]
**Describe the bug**
Since a change made in rptools/dicelib#28, `getRolled()` and `getNewRolls()` are no longer reliable when called within a UDF.  Duplicate values are inserted into the results depending on lines of additional instructions.

**To Reproduce**
1. Create macro on a Lib:token, (I used "bugTest@Lib:test") with contents like:
```
[h: 1d20]
[h: rolls_1 = getNewRolls()]
[h: 1d20]
[h: rolls_2 = getNewRolls()]
[h: macro.return = json.set("","rolls_1", rolls_1, "rolls_2", rolls_2, "all_rolls", getRolled())]
```
2. Define a UDF for the macro created above: 
`[defineFunction("bug.bugTest", "bugTest@Lib:test", 0, 1)]`
3. Call the new UDF: 
`[r: bug.bugTest()]`

Output produced like:
> `{"rolls_1":[2],"rolls_2":[2,2,14],"all_rolls":[2,2,2,14,2,14]}`

**Expected behavior**
`getNewRolls()` and `getRolled()` should work as originally intended - the above steps should produce output like:
> `{"rolls_1":[2],"rolls_2":[14],"all_rolls":[2,14]}`

**MapTool Info**
- Version: 1.7, Dicelib version: 1.6+

**Additional context**
https://github.com/RPTools/dicelib/blob/9720528203b43c71264546ab1a74e4cf3bbe6c44/src/main/java/net/rptools/common/expression/ExpressionParser.java#L222-L244
The problem is occurring only in UDFs because the UDF gets parsed within the context of the first RunData object created by the ExpressionParser.  Normal iterative execution remains at the top level, and does not typically have an old RunData object to keep.

Fix PR coming soon.

**Comment by selquest** [comment]
@Phergus just making sure this doesn't slip through cracks, since I know most issues are in the MapTool project proper

**Comment by Phergus** [comment]
Thanks!  Will add an issue to MT to pull in the updated library.

**Comment by Phergus** [comment]
Release 1.6.2 created with fix.
