### ISSUE TITLE
Allow to specify whether the caller wants the evaluation of an expression to be made deterministic

### ISSUE THREAD

**Issue by nmeier** [RPTools/dicelib#43]
Currently all evaluations create a deterministic parser - this has two disadvantages IF determinism is not required 

1. it takes extra parsing time
2. it flattens objects unnecessarily, thus causing slow json handling in caller MapTool

see https://github.com/RPTools/maptool/issues/1898

Proposal : add optional parameter to not create a deterministic result that can be utilized upstream

**Comment by Phergus** [comment]
PR merged.  Will do a release and then open a MapTool issue to bump the dicelib version.

**Comment by Phergus** [comment]
Dicelib 1.6.3 released.
