### ISSUE TITLE
ShadowRun 5 Dice Roll

### ISSUE THREAD

**Issue by phi1010** [RPTools/dicelib#62]
## Glitch Criterion

Shadowrun 5 dice rolls have a different glitch criterion than shadowrun 4 does, see also:
https://forums.shadowruntabletop.com/index.php?topic=17513.0
https://shadowrun5.tumblr.com/post/72391449769/ge%C3%A4nderte-regeln-patzer

In Shadowrun 4, a glitch occurs if **half or more** of the dice (tosses?) result in a "1".
In Shadowrun 5, a glitch occurs if **more than half** of the dice result in a "1" -- glitching and having success is perpendicular, both or neither can occur.

Rolling 6,1 with two dice would be a glitch in Shadowrun 4 rules, but not in Shadowrun 5.
Rolling 1,1 with two dice would still be a critical glitch in both editions. 

## Exploding Dice: 

I've never read Shadowrun 4 rules, and do not know for sure whether it specifies dice or tosses to be used as criterion with glitches.

These two values differ on exploding dice (Where Shadowrun 5 does not add dice, but rerolls them.):
The current SR4 implementation considers two dice rolling 6,6,6,6,1,1 not to be a glitch, because less than half of tosses resulted in a "1".
The future SR5 implementation will consider two dice rolling 6,6,6,6,1,1 to be a glitch, since with two ones, more than half (=1) of the dice pool (=2, not 6) have resulted in a "1".

I'd expect dice, since Shadowrun 5 specified dice, and I haven't read about anybody noticing a difference. 
However currently implemented is a comparison with tosses, not dice; where I expect this to be a programming mistake caused by overwriting a parameter variable used later, in expectation to be using the original value.

The current PR uses tosses (as implemented before, to avoid any unexpected changes) for SR4, and uses dice for SR5.

## Gremlins

Gremlins is a specific negative player character trait, increasing the likeliness of glitches by reducing the number of dice required to result in "1" to cause a glitch.

In SR5, gremlins-caused glitches are suggested to be represended by inexplicable cirumstances. To simplify this, glitches only happing due to the reduced dice number, which would not be a glitch otherwise, now show up as `*Critical Gremlin Glitch*` or `*Gremlin Glitch*` instead of `*Critical Glitch*` or `*Glitch*`.

**Comment by Phergus** [comment]
Tested in MT dev branch.  Appear to be working.
