### ISSUE TITLE
Bounded rolls: one more function and two more dice expressions

### ISSUE THREAD

**Issue by aRTy42** [RPTools/dicelib#92]
**Is your feature request related to a problem? Please describe.**
Not based on a problem. The wiki page [Dice Expressions](https://wiki.rptools.info/index.php/Dice_Expressions) has a few rather exotic expressions and corresponding functions, but not all expressions and functions exist that one might expect based on those that are listed there.

Expression | exists? | Function | exists?
--- | --- | --- | ---
XdYaZuW | :heavy_check_mark: | rollAddWithUpper | :heavy_check_mark:
XdYsZlW | :heavy_check_mark: | rollSubWithLower | :heavy_check_mark:
XdYaZlW | :x: | rollAddWithLower | :heavy_check_mark:
XdYsZuW | :x: | rollSubWithUpper | :x:

**Describe the solution you'd like**
Add the two missing expressions and the one missing function. I've already been looking at the files and intend to make a PR myself that provides the changes.

**Describe alternatives you've considered**
—

**Additional context**
Selquest told me on Discord that a feature request should be made, so that my PR has a corresponding issue.

**Comment by Phergus** [comment]
Documentation complete.

**Comment by Phergus** [comment]
Tested with current dev build.  Working as described.
